---
title: "Linear Models workshop (#4) of the R QCBS Workshops Series"
topics: "ANCOVA"
date: 12/11/2024
link: https://r.qcbs.ca/workshops/r-workshop-04/
---

```{r}
# 1. Load libraries
library(car)
library(dplyr)
library(vegan)
library(MASS)
library(effects)
library(e1071)
library(gtsummary)
```

# 2. Load and manipulate the dataframe 
```{r}
# 2.1 Load the dataframe
bird <- read.csv("birdsdiet.csv")
str(bird)
```
```{r}
# 2.2 Transform some variables
bird$logMass <- log10(bird$Mass)
bird$logMaxAbund <- log10(bird$MaxAbund)
```

# 3. Running ANCOVA
```{r}
# 3.1 Running on an example dataset
ancova.example <- lm(uptake ~ conc*Treatment, data = CO2)
anova(ancova.example)
```
```{r}
# 3.2 Adjusted mean using effects package
adj.mean.ex <- effect("Treatment", ancova.example)
plot(adj.mean.ex)
```
```{r}
# 3.3 Set up the main dataframe
lm1 <- lm(formula = logMaxAbund ~ logMass + Diet, data = bird)
summary(lm1)
```
```{r}
adjusted.mean <- effect("Diet", lm1)
plot(adjusted.mean)
```
